# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.13
target-version = "py313"

[lint]
select = ["E", "F", "C", "A", "ISC", "N", "UP"]
ignore = ["A003", "UP047"]
preview = true

[lint.per-file-ignores]


[format]
quote-style = "double"
